#DAY 3 : Python Recap AND NumPy Basics



 **Part 1** : quick pyhton recap


In [9]:
# mini pyhton challenge

numbers=[10,20,30,40,50]
def sq_list(lst):
     a=[]
     for x in lst :
       a.append(x**2)
     return a
print(sq_list(numbers))


[100, 400, 900, 1600, 2500]


In [10]:
# problem 2
# in this i have to doule the no the list
def dou_num(lst):
  b=[]
  for x in lst:
    b.append(x+x)
  return b
print(dou_num(numbers))


[20, 40, 60, 80, 100]


## what is numpy ?

**NumPy** = numerical python
it helps you:
* Works with big lists ( called arrays)
* Do math super fast
* Built the base for ml models



In [11]:
# importying numpy
import numpy as np


In [13]:
# creating  a numpy array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [14]:
#arrays of zero
zeros = np.zeros([2,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# arrays of ones
ones = np.ones(
    [3,3])
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# creating a range of array
range_arr = np.arange(1,10,2)
print(range_arr)

[1 3 5 7 9]


In [22]:
# Reshape an array
reshaped = np.array([1,2,3,4,5,6]).reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


## Todays practice


In [23]:
arrp =np.zeros([4,4])
print(arrp)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
ran = np.random.rand(3,3)
print(ran)

[[0.42783391 0.13135108 0.10761349]
 [0.59665392 0.50066619 0.63533009]
 [0.45626024 0.09193313 0.50121248]]


In [30]:
arr2 = np.array([1,2,3,4,5,6]).reshape(3,2)
print(arr2)

[[1 2]
 [3 4]
 [5 6]]
