# Day 4: NumPy indexing, slicing and operations

**1. Indexing and slicing**

In [3]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[1:4])
print(arr[-1])

10
[20 30 40]
50


2D array

In [5]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix[1][2])


6


**2. Array operations**

In [6]:
a= np.array([1,2,3])
b= np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


**3. Broadcasting** : when NumPy adjust Dimensions automatically

In [7]:
print(a+5)

[6 7 8]


**4. Useful numpy functions**

In [9]:
arr = np.array([10,20,30,40,50])

print(np.mean(arr)) # used to find avg of value in array
print(np.max(arr))  # used to find maximum value in a array
print(np.min(arr))  # used to find minimum value in a array
print(np.sum(arr))  # to find sum of all values in an array

30.0
50
10
150


# Practice


In [20]:
# slicing practice
# in this i have to slice the last two rowsx of 3x3 array
parr = np.random.rand(3,3)
print(parr[-2: : ])
# now multipy by 10
print(parr*10)

[[0.01154975 0.90916642 0.58215921]
 [0.24734658 0.01063632 0.40648249]]
[[6.3201375  7.00273803 6.45976124]
 [0.11549751 9.09166422 5.82159207]
 [2.47346577 0.10636315 4.06482485]]
