## NUMPY  

## why use numpy?


*   Numpy provides efficient storage
*  It also provides better ways of handling data for processing
*  It is fast
*  Numpy uses relatively less memory to store data


In [2]:
import numpy as np

**Creating a numpy array**

In [ ]:
#two dimentional array
myarr = np.array([[1,2,3]])
# one dimentional array
arr = np.array([1,2,3,4,5,6])
print(myarr)

[[1 2 3]]


In [ ]:
myarr

array([[1, 2, 3]])

**Accessing element from array**

In [ ]:
print(myarr[0,2])

3


**Information about array**

In [ ]:
myarr.shape # tells about rows and columns

(1, 3)

In [ ]:
myarr.dtype # tells about data type

dtype('int64')

**reshaping array**

In [ ]:
arr = arr.reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

**revel**

In [ ]:
# revel makes array as one dimnetional or you can say it hepls to regain its orignal shape
arr = arr.ravel()
arr

array([1, 2, 3, 4, 5, 6])

## Array creation methods



1.   Conversion from other Python structures (e.g., lists, tuples)
2.   Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)
3.   Reading arrays from disk, either from standard or custom formats
4.   Creating arrays from raw bytes through the use of strings or buffers
5.   Use of special library functions (e.g., random)



**1.Conversion from other Python structures **

In [ ]:
# above already done

**2. Intrinsic numpy array array creation objects**

In [ ]:
# arrays of zeros
zeros=np.zeros((2,5))
print(zeros)
print(zeros.dtype)
print(zeros.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
(2, 5)


In [ ]:
# range of arrays
rng = np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
# linspace provides Equally linearly spaced elements in a range
lspace = np.linspace(1,5,12)
print(lspace)

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


# NUMPY AXIS

In NumPy, the axis parameter is used to specify the direction along which operations (like sum, mean, min, max, etc.) are performed on arrays.

NumPy arrays can be multi-dimensional (1D, 2D, 3D, etc.), and the axis helps us choose whether to apply a function across rows or columns.

Basic Concept:
*	Axis 0 → Operates column-wise (i.e., down the rows)
*	Axis 1 → Operates row-wise (i.e., across the columns)

In [7]:
x = [[1,2,3],[4,5,6],[7,1,0]]
aax = np.array(x)
aax

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
aax.sum(axis=0)

array([12,  8,  9])

In [ ]:
aax.sum(axis=1)

array([ 6, 15,  8])

In [ ]:
# T use for trans pose
aax.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [ ]:
aax.ndim # tells how many dimentions are there

2

In [ ]:
aax.size # tells about the size

9

In [5]:
##  argmax function :- it give the index of largest element
m =np.array([1,2,3,567,5])
print(m.argmax())
#  argmin function :- it gives the index of smallest element
print(m.argmin())
# argsort function :- sort the arrray
print(m.argsort())

3
0
[0 1 2 4 3]


**Mathematical operations in numpy**
numpy gives us feature to do matrix operations

In [17]:
m2=np.array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])
m1 = np.array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [18]:
m1 + m2  # sum with two dimentional array

array([[1, 5, 9],
       [2, 6, 3],
       [5, 7, 0]])

In [19]:
m1*m2 # multiplication with two dimentional array

array([[ 0,  4, 14],
       [ 0,  5,  2],
       [ 6,  6,  0]])

In [20]:
m1*2 # multiplication with constant

array([[ 2,  8, 14],
       [ 4, 10,  2],
       [ 6, 12,  0]])

In [21]:
np.sqrt(m1) # square root each element in array

array([[1.        , 2.        , 2.64575131],
       [1.41421356, 2.23606798, 1.        ],
       [1.73205081, 2.44948974, 0.        ]])

In [22]:
m2.sum() # gives sum of all elements in array

np.int64(9)

In [26]:
m2.max()  #gives the largest element in array

np.int64(2)

In [27]:
m2.min() # gives the smallest element in array

np.int64(0)

In [30]:
np.where(m1==0) # used to find element in array

(array([2]), array([2]))

In [31]:
np.count_nonzero(m1) # used to count non zero elements in array

8

**How take less space ?**
----



In [33]:
import sys
py_ar=[0,1,2,3]
np_ar=np.array([0,1,2,3])

In [35]:
sys.getsizeof(1) * len(py_ar)

112

In [36]:
np_ar.itemsize * np_ar.size

32

**you can clearly see above that np array is taking less space then pyhton array**

# This guide explores the NumPy library, with a focus on mastering key topics that are essential for practical and effective use